version: 3.8.0
services:
    dramaload:
        working_dir: /app
        build: .
        container_name: dramaload
        env_file: ./.env
    # mongodb:
    #     image: mongo
    #     container_name: mongodb
    #     ports:
    #       - 27017:27017
    #     volumes:
    #         - ./data:/data/db
